### ISSUE TITLE
Fix broken links in `README.md` file and adjust issues templates

### ISSUE THREAD

**Issue by mateuseap** [CinCoders/cinnamon#1]
## Description

There are two broken links in `README.md` file, one is the link to **usage guide** and the other is the link to **contribution guide**. Also, there's some problem with the **issues templates**, when you're creating a new issue, the templates don't show up, it just starts a new blank issue.

When creating a new issue, it's expected to show up a page like this containing the two templates that are present in this project (**BUG_REPORT** and **FEATURE_REQUEST**):
![image](https://i.imgur.com/JDmr2ff.png)

But instead, just a new blank issue shows up:
![image](https://user-images.githubusercontent.com/52019009/230383834-e9ad476a-41a2-4511-bc2a-364b13b4f547.png)

**Comment by dcruzb** [comment]
Thx for pointing these issues @mateuseap!
