### ISSUE TITLE
[feature]: The width of the dialog should be defined according to its children

### ISSUE THREAD

**Issue by dcruzb** [CinCoders/cinnamon#33]
### Current Behavior

The dialog width is being set to a default  width and creates a scrollbar to display the children.

### Expected Behavior

Increase the width of the dialog according to its children, limited to the view width.

### Version

0.1.6

### What browsers are you seeing the problem on?

chrome

**Comment by ldcss** [comment]
- Remove max-width property from default MUI dialog style
