### ISSUE TITLE
[Bug]: Error loading Navbar with users without Name

### ISSUE THREAD

**Issue by dcruzb** [CinCoders/cinnamon#73]
### Current Behavior

When an user don't have the attribute "Name" it is not possible to login. The console displays an error regarding the first letter of the name that is lacking.

### Expected Behavior

Enable users without Name defined to login to the system. Another information should be used when there is no name, such as the Username

### Version

1.0.3

### What browsers are you seeing the problem on?

Any

**Comment by Vidhanvyrs** [comment]
can you assign me the issue i think i have a solution for it

**Comment by Vidhanvyrs** [comment]
hey @dcruzb  I think i found the solution please check the PR!

**Comment by dcruzb** [comment]
Thank you for contributing @Vidhanvyrs!!
I've reviewed you PR and requested some changes, let me know if there is anything I may help!

**Comment by Vidhanvyrs** [comment]
sure thing I'll definitely have a look at them

**Comment by dcruzb** [comment]
Thanks @Vidhanvyrs, I've accepted the PR!
